### ISSUE TITLE
vstest.console /testcasefilter:query doesn't filter tests

### ISSUE THREAD

**Issue by AArnott** [xunit/visualstudio.xunit.integration#3]
When running xunit tests at the command line via the VS test runner:

    vstest.console /usevsixextensions /testcasefilter:somequery

The tests are not filtered. From what I understand, the filter must be applied by the unit test adapter (xunit in this case). So it seems it's a missing feature here.

**Comment by Steve-Fenton** [comment]
:+1: 

I'm having this problem too - are there any workarounds for Visual Studio Online builds?

**Comment by onovotny** [comment]
@AArnott are there docs about how that /testcasefilter parameter makes it into the `ITestDiscoverer` or `ITestExecutor` implementations and what the contents of that parameter represent?

You can see the vs runner here:
https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.testadapter/VsTestRunner.cs

There's no specific filtering being applied. Is the filter for traits? For assemblies? For a test name? How do we get that param value it in there? Etc?

**Comment by onovotny** [comment]
Seems to be doc'd here:
http://blogs.msdn.com/b/vikramagrawal/archive/2012/07/23/running-selective-unit-tests-in-vs-2012-rc-using-testcasefilter.aspx

**Comment by AArnott** [comment]
Glad you found it (because I didn't know where the doc was). IIRC there is another MSFT employee who has an xunit fork where he added support for this. Let me know if you want me to direct you to it for reference.

**Comment by onovotny** [comment]
If someone already started this, that code would be very welcome

**Comment by AArnott** [comment]
Here is the [relevant commit](https://github.com/Tofudebeast/visualstudio.xunit/commit/bfd2a0a64bbd4324094ea0d15ccc9ef0433c82e1).

**Comment by onovotny** [comment]
Resolved with https://github.com/xunit/visualstudio.xunit/commit/6de34af0df51e139d754746adeb1fb3656fe972c. Should be in the 2.1-beta4 VS Runner package.
